### ISSUE TITLE
sources API broken in dev version

### ISSUE THREAD

**Issue by danohu** [OpenOil-UG/aleph#11]
doesn't seem to affect the production version, so maybe it's just bogus data in the dev db?

ERROR:aleph.core:Exception on /api/1/sources [GET]
Traceback (most recent call last):
  File "/home/dan/.virtualenvs/aleph_dev/local/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/dan/.virtualenvs/aleph_dev/local/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/dan/.virtualenvs/aleph_dev/local/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/dan/.virtualenvs/aleph_dev/local/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/dan/.virtualenvs/aleph_dev/local/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/data/search/aleph_dev/aleph/views/sources_api.py", line 27, in index
    etag_cache_keygen(max(latest))
TypeError: can't compare datetime.datetime to NoneType

**Comment by danohu** [comment]
removing milestone -- this is only affecting the dev installation, so not urgent to fix.
